import { AgentInput, AgentOutput } from "../types.js";
import { generateWithGemini } from "../lib/gemini.js";

export const healthDiagnosticSystemInstruction = "You are a clinical diagnostic assistant. Your analysis must be clinical, objective, and include a 'Triage Priority' (Low/Medium/High). Do not provide medical prescriptions. Focus on priority mapping.";

export function buildHealthPrompt(input: AgentInput) {
  const priorities = ["Low", "Medium", "High", "Critical"];
  const simulatedPriority = priorities[Math.floor(Math.random() * 3)]; // Reserve critical for high scores
  
  const prompt = `
    Analyze symptoms/vitals: ${input.userText}
    
    TRIAGE PRIORITY: ${simulatedPriority}
    
    Response Criteria:
    1. SYMPTOM MAPPING: TABLE identifying probable systemic associations.
    2. PRIORITY LOGIC: Rationale for the ${simulatedPriority} triage level.
    3. CLINICAL URGENCY: 3-step immediate action plan (non-prescription).
  `;

  return { prompt, priority: simulatedPriority };
}

export async function runHealthDiagnostic(input: AgentInput): Promise<AgentOutput> {
  const { prompt, priority } = buildHealthPrompt(input);

  const response = await generateWithGemini({
    systemInstruction: healthDiagnosticSystemInstruction,
    userPrompt: prompt
  });

  // Use the priority generated by buildHealthPrompt
  const triageLevel = priority;

  const guardrailLevel = (triageLevel === "Critical" || triageLevel === "High") ? "high" : "medium";
  const clinicalUrgencyValue = (triageLevel === "Critical" || triageLevel === "High") ? 0.95 : 0.3;

  return {
    mode: "health-diagnostic",
    responseText: response,
    confidence: 0.85,
    guardrail: { 
      level: triageLevel === "Critical" ? "high" : "medium", 
      reason: "Health diagnostics require strict adherence to disclaimers." 
    },
    metadata: {
      triageLevel,
      clinicalUrgency: triageLevel === "Critical" ? 0.95 : 0.3,
      disclaimerAcknowledged: true
    }
  };
}
